import * as React from 'react';
import Head from 'next/head';
import Index from '../src/components/index';

export default function Home() {
    return (
        <>
            <Head>
                <title>Looking Glass</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Index />
        </>
    );
}
