import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import LocationBar from '../src/components/location-bar/location-bar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <p>dfgsdfg</p>


        <LocationBar />
    </>
  );
};

export default Home;
